### ISSUE TITLE
copier cannot create dirs

### ISSUE THREAD

**Issue by wizzard0** [Evgenus/spa#72]
```
Error: ENOENT, no such file or directory 
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.writeFileSync (fs.js:966:15)
    at Builder._write_file (.\node_modules\spa\lib\index.js:546:15)
    at Builder._encode (.\node_modules\spa\lib\index.js:769:14)
    at Builder.build (.\node_modules\spa\lib\index.js:1048:10)
    at Gulp.gulp.task.gulp.src.pipe.ts.declarationFiles (.\gulpfile.js:57:33)
    at module.exports (.\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (.\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (.\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at .\node_modules\gulp\node_modules\orchestrator\index.js:279:18
```

**Comment by Evgenus** [comment]
will fix
